### ISSUE TITLE
Internal server error on authorization attempt

### ISSUE THREAD

**Issue by blackary** [TheClimateCorporation/api-example#9]
Problem: 500 error on authorization attempt.

Steps to reproduce:
1) Follow the installation instructions
2) Go to http://localhost:8080/home
3) Click on login with fieldview button
4) Get directed to https://climate.com/static/app-login/index.html?scope=openid+fields%3Aread+imagery%3Awrite&page=oidcauthn&response_type=code&client_id=partner-fooco&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Flogin-redirect
5) Put in credentials, get prompted for accepting account access. 
6) Click allow.

Result:
I get sent to https://climate.com/api/oidc/authorize with the following content:
> HTTP ERROR 500
> Problem accessing /oidc/authorize. Reason:
> Internal Server Error

**Comment by mtkp** [comment]
@blackary thanks for pointing this out! the underlying issue here is that `partner-fooco` isn't a registered ID in our system. but our http response should be better. we'll have a fix out for that shortly. in the meantime i'll update the example to be a bit more clear about example value for the `CLIMATE_API_ID`.

**Comment by mtkp** [comment]
@blackary we've pushed out a fix, so you'll now get a 400 with a message ("Invalid client")
